name: iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Flutter pub get
        run: flutter pub get
      - name: Create platforms
        run: flutter create .
      - name: Build iOS (no code signing)
        run: flutter build ios --release --no-codesign
      - name: Archive app
        run: |
          mkdir -p build_artifacts
          zip -r build_artifacts/Runner.app.zip build/ios/iphoneos/Runner.app
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-runner-app
          path: build_artifacts/Runner.app.zip
