name: iOS Signed IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Flutter pub get
        run: flutter pub get
      - name: Create platforms
        run: flutter create .
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Install fastlane
        run: sudo gem install fastlane -NV
      - name: Decode signing cert
        env:
          P12_BASE64: ${{ secrets.IOS_SIGNING_CERT_P12_BASE64 }}
          P12_PASSWORD: ${{ secrets.IOS_SIGNING_CERT_PASSWORD }}
        run: |
          echo "$P12_BASE64" | base64 --decode > signing.p12
          security create-keychain -p "" build.keychain
          security import signing.p12 -k ~/Library/Keychains/build.keychain -P "$P12_PASSWORD" -A
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain
      - name: Decode provisioning profile
        env:
          MOBILEPROVISION_BASE64: ${{ secrets.IOS_MOBILEPROVISION_BASE64 }}
        run: |
          echo "$MOBILEPROVISION_BASE64" | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          UUID=$(grep -a -o '<key>UUID</key>\n<string>.*</string>' profile.mobileprovision | sed -n 's/.*<string>\(.*\)<\/string>/\1/p')
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
      - name: Build iOS (archive)
        run: |
          flutter build ios --release
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/ios/archive/Runner.xcarchive archive DEVELOPMENT_TEAM="${{ secrets.APPLE_TEAM_ID }}" PRODUCT_BUNDLE_IDENTIFIER="${{ secrets.APPLE_BUNDLE_ID }}"
      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive -exportPath build/ios/ipa -exportOptionsPlist ios/ExportOptions.plist
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
